FROM python:3-alpine

LABEL author="Rajeev Kumar Gupta"
LABEL description="Dockerfile for Python script which prints Hello, Name"

COPY hello-world.py /app/
ENV NAME=Rajeev
CMD python3 /app/hello-world.py

