---
- hosts: localhost
  user: root
  tasks:
    - name: install apache
      action: yum name=httpd state=installed

    - name: configure apache
      copy: src=files/httpd.conf dest=/etc/httpd/conf/httpd.conf

    - name: restart apache
      service:
        name: httpd
        state: restarted
