FROM continuumio/anaconda3
RUN apt update 
RUN apt -y upgrade 
RUN apt -y install python3-dev python3-pip 
RUN pip3 install -U virtualenv 
RUN pip install --upgrade pip 
RUN pip install pillow  
RUN conda update -n base -c defaults conda
RUN conda create -n tf tensorflow pip
